### ISSUE TITLE
Score never improves

### ISSUE THREAD

**Issue by pender** [andreimuntean/A3C#1]
I've been training for something like 2.5 days now and have yet to improve beyond the following:

`[2017-04-07 10:06:20,289] Finished episode. Total reward: -21. Length: 1245.`

I'm using default hyperparameters, just using `sh train.sh` to launch training. Computer is an Intel Core i7-2600 CPU @ 3.40GHz. Eight threads run on my system -- do I need more than that to see improvement?

I did make a couple of changes, which I don't think should have affected the result but listing them here just in case:

- Changed instances of `python3` in `train.sh` to `python` (so that it would run with Python 2.7)
- Added `config.gpu_options.allow_growth = True` after each invocation of `tf.ConfigProto()` (I am running on a GPU-enabled TF install and without the change, each thread would try to reserve almost all of the GPU memory, which would cause each thread after the second or third to fail with a CUDA out of memory error even though the code doesn't ever use the GPU.)

Any advice?

**Comment by andreimuntean** [comment]
Thanks for trying it out and I apologize for the late reply! (I've fixed my notifications to prevent this lateness from repeating itself)

You should definitely see improvements after a few hours of training on your system. The migration from Python 3 to 2 might have spawned some insidious bugs. For example at **a3c.py**, did you change

`maxval = math.sqrt(6 / (num_input_params + num_output_params))`

to correctly perform floating-point division? In Python 3, that operation returns a double. In Python 2, it returns an integer (in your case it probably returned 0 all the time, initializing the neural network very poorly).

I hope this helps, even if you probably moved to something else. :-)

**Comment by pender** [comment]
Aha -- thanks for the pointer, that makes perfect sense. Closing this out.
